<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>starter</AssemblyName>
    <RootNamespace>ToolDock.Starter</RootNamespace>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ToolDock.Common\ToolDock.Common.csproj" />
  </ItemGroup>
</Project>
